version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:1000"
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/hdd/webs:/srv
      - /mnt/hdd/filebrowser-config/filebrowser.db:/database/filebrowser.db
      - /mnt/hdd/filebrowser-config/settings.json:/.filebrowser.json
    ports:
      - "8087:80"

# user: admin password:(en logs)