version: "3.7"

services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    depends_on:
      - photoprism-db
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: photoprism-db:3306
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DATABASE_PASSWORD: ${PHOTOPRISM_DB_PASSWORD}
      PHOTOPRISM_SITE_URL: "https://photos.${DOMAIN}/"
    volumes:
      - ./data/photoprism/originals:/photoprism/originals
      - ./data/photoprism/storage:/photoprism/storage

  photoprism-db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: photoprism
      MARIADB_USER: photoprism
      MARIADB_PASSWORD: ${PHOTOPRISM_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${PHOTOPRISM_DB_PASSWORD}
    volumes:
      - ./data/photoprism-db:/var/lib/mysql
    command: >
      mariadbd
      --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max-connections=512
      --innodb-rollback-on-timeout=OFF
      --innodb-lock-wait-timeout=120
