services:
  web-palantir:
    image: nginx:alpine
    container_name: web-palantir
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - /mnt/hdd/webs/web-palantir:/usr/share/nginx/html:ro
