services:
  web-campamento:
    image: nginx:alpine
    container_name: web-campamento
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - /mnt/hdd/webs/web-campamento:/usr/share/nginx/html:ro
